### ISSUE TITLE
friendly names for players

### ISSUE THREAD

**Issue by b0ggyb33** [TeamModular/TowBully#15]

**Comment by b0ggyb33** [comment]
even if its just "Player 1"etc. and a colour rather than "PlayerWithKeyboard"

**Comment by b0ggyb33** [comment]
currently splattered all over the place - ideally we need a getName method/property on Player so we can support naming them in the future

**Comment by MrBunsy** [comment]
getname added, players can't choose their own name yet

**Comment by b0ggyb33** [comment]
use random name generator from pebble
