### ISSUE TITLE
Derby tracks with obstacles

### ISSUE THREAD

**Issue by b0ggyb33** [TeamModular/TowBully#25]
- [ ] oil slicks
- [ ] gravel pits
- [ ] destructible buildings

**Comment by b0ggyb33** [comment]
- [ ] oil slicks
- [ ] gravel pits
- [ ] destructible buildings

**Comment by MrBunsy** [comment]
commited and pushed the master work for a simple derby square/rectangle map.

TODO still: set zoom level/aspect ratio so this always fills the screen.  Anything other than a square of gravel

**Comment by MrBunsy** [comment]
added oil spills
