### ISSUE TITLE
track generation bug

### ISSUE THREAD

**Issue by b0ggyb33** [TeamModular/TowBully#40]
![untitled](https://cloud.githubusercontent.com/assets/4669850/13889147/e6362890-ed3c-11e5-95f6-af2ed63c590e.jpg)

**Comment by b0ggyb33** [comment]
![53776_pretty](https://cloud.githubusercontent.com/assets/4669850/13889180/0d7c65cc-ed3d-11e5-9825-3c9f51fc5dac.png)

**Comment by b0ggyb33** [comment]
53776

**Comment by MrBunsy** [comment]
should now be impossible
